# Generated by Django 3.0.7 on 2020-07-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Machinery',
        ),
        migrations.DeleteModel(
            name='Pesticide',
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
