# Generated by Django 3.0.7 on 2020-08-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_items',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
