# Generated by Django 3.0.7 on 2020-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_items', '0002_auto_20200804_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_items',
            name='amount_to_pay',
            field=models.FloatField(null=True),
        ),
    ]
